### PR TITLE
Fix grammatical error

### PR DESCRIPTION
**Pull request by okcoker**

### CODE REVIEW

**Comment by domenic** [comment]
This isn't a grammar error. THe text as written is correct, and your correction is incorrect.

**Comment by okcoker** [comment]
So unresolved === pending? The "necessarily" wording is throwing me off when reading the sentence.

As in, if "not" is incorrect, I'd expect the sentence to just say something like:
"A promise whose fate is unresolved is pending."

Is that correct?

**Comment by getify** [comment]
@okcoker-

I think "necessarily" in the original text should be understood to mean "required to be".

**Comment by domenic** [comment]
Unresolved implies pending, but is not ===.

See e.g. http://www.brainyquote.com/quotes/quotes/f/franklloyd127723.html if you've never heard this use of necessarily before.

**Comment by okcoker** [comment]
Ah, okay thanks. Makes sense now.

**Pull request closed without merging**
